name: Build and deploy Next.js app to Azure Web App - den-test1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: npm install and build
        run: |
          npm ci
          npm run build
        env:
          CI: true
          NEXT_LINT_IGNORE_WARNINGS: true

      - name: Run tests if available
        run: npm test --if-present
        env:
          CI: true

      - name: Zip artifact for deployment
        run: zip release.zip .next package.json next.config.mjs public -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_290ECCD305B44146956C8BA9CA1F4515 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_548E152AA7A14FA99EFA9FADAFA37BFA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7D9946B61264B6985A4CD42FE0C1453 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'den-test1'
          slot-name: 'Production'
          package: .

      - name: Delete zip file
        run: rm release.zip